---
:base_url: https://lirias2test.libis.kuleuven.be/elements-cache/rest/publications?affected-since=
:base_delete_url: https://lirias2test.libis.kuleuven.be/elements-cache/rest/deleted/publications?per-page=1000&deleted-since=
:user: john
:password: doesNotKnow
:last_run_updates: '2018-03-14T20:45:36.88+01:00'
:last_run_deletes: '2018-06-11T10:21:33.610Z'
